HL_SLIPPAGE_PERCENTS = 0.5 
AEVO_SLIPPAGE_PERCENTS = 0.5
DRIFT_SLIPPAGE_PERCENTS = 0.5

HL_SLIPPAGE = HL_SLIPPAGE_PERCENTS / 100
AEVO_SLIPPAGE = AEVO_SLIPPAGE_PERCENTS / 100
DRIFT_SLIPPAGE = DRIFT_SLIPPAGE_PERCENTS / 100

COINS = ['BTC', 'ETH', 'SOL']

HL_DECIMALS = {'BTC': 5,'ETH': 4, 'SOL': 2}
HL_TAKER_FEE = 0.025 / 100
HL_MAKER_FEE = -0.002 / 100 