HL_SLIPPAGE_PERCENTS = 0.5 
AEVO_SLIPPAGE_PERCENTS = 0.5
DRIFT_SLIPPAGE_PERCENTS = 0.5

HL_SLIPPAGE = HL_SLIPPAGE_PERCENTS / 100
AEVO_SLIPPAGE = AEVO_SLIPPAGE_PERCENTS / 100
DRIFT_SLIPPAGE = DRIFT_SLIPPAGE_PERCENTS / 100

MIN_POSITION_TIME = 5 * 60 
MAX_POSITION_TIME = 15 * 60

COINS = ['BTC', 'ETH', 'SOL']

HL_DECIMALS = {'BTC': 5,'ETH': 4, 'SOL': 2}
HL_PRICE_DECIMALS = {'BTC': 1,'ETH': 2, 'SOL': 4}
AEVO_PRICE_DECIMALS = {"BTC": 1, "ETH": 2, 'SOL': 3}

HL_TAKER_FEE = 0.025 / 100
HL_MAKER_FEE = -0.002 / 100 